//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.27 at 06:04:46 PM PST 
//


package ZomboidJavaHook.mac;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlType;

import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "array")
public class Array implements Variant {

    @XmlElements({
            @XmlElement(name = "key", type = Key.class, required = false),
            @XmlElement(name = "string", type = PlistString.class, required = false),
            @XmlElement(name = "array", type = Array.class, required = false)
    })
    protected List<Variant> elements;

    @Override
    public List<Variant> getArray() {
        return elements;
    }

    public String getString() {
        return null;
    }
}
