name: Release Pipeline

on:
  push:
    tags: ['v*']

jobs:
  Windows:
    name: Windows Release
    if: ${{ !contains(github.event.head_commit.message, '[CI Skip]') }}
    uses: Olipro/PZHook/.github/workflows/ci.yml@github
    with:
      isRelease: true
      target: windows-latest
      archive: '-Win64'
    secrets:
      GITHUBTOKEN: ${{secrets.GITHUB_TOKEN}}
  Linux:
    name: Linux Release
    if: ${{ !contains(github.event.head_commit.message, '[CI Skip]') }}
    uses: Olipro/PZHook/.github/workflows/ci.yml@github
    with:
      isRelease: true
      target: ubuntu-latest
      archive: '-Linux64'
    secrets:
      GITHUBTOKEN: ${{secrets.GITHUB_TOKEN}}
  Mac:
    name: MacOS Release
    if: ${{ !contains(github.event.head_commit.message, '[CI Skip]') }}
    uses: Olipro/PZHook/.github/workflows/ci.yml@github
    with:
      isRelease: true
      target: macos-latest
      archive: '-MacOS'
    secrets:
      GITHUBTOKEN: ${{secrets.GITHUB_TOKEN}}
